// <auto-generated />
using System;
using ASPNETCoreApp;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EFCoreConsoleApp.Migrations
{
    [DbContext(typeof(UniversityRoomFundDbContext))]
    [Migration("20220417103949_ComputedColumn")]
    partial class ComputedColumn
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ASPNETCoreApp.Models.Building", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Buildings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "2-й учебный корпус"
                        },
                        new
                        {
                            Id = 2,
                            Name = "4-й учебный корпус"
                        });
                });

            modelBuilder.Entity("ASPNETCoreApp.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("FacultyId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("FacultyId");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FacultyId = 1,
                            Name = "Кафедра информационной безопасности"
                        },
                        new
                        {
                            Id = 2,
                            FacultyId = 1,
                            Name = "Кафедра интеллектуальных информационных технологий"
                        },
                        new
                        {
                            Id = 3,
                            FacultyId = 1,
                            Name = "Кафедра системного программирования"
                        },
                        new
                        {
                            Id = 4,
                            FacultyId = 2,
                            Name = "Национальное общество прикладной лингвистики"
                        },
                        new
                        {
                            Id = 5,
                            FacultyId = 2,
                            Name = "Just English"
                        });
                });

            modelBuilder.Entity("ASPNETCoreApp.Models.Faculty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("BuildingId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("BuildingId");

                    b.ToTable("Faculties");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BuildingId = 1,
                            Name = "Факультет вычислительной математики и кибернетики"
                        },
                        new
                        {
                            Id = 2,
                            BuildingId = 2,
                            Name = "Факультет иностранных языков и регионоведения"
                        });
                });

            modelBuilder.Entity("ASPNETCoreApp.Models.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("BuildingId")
                        .HasColumnType("int");

                    b.Property<double>("CeilingHeight")
                        .HasColumnType("float");

                    b.Property<int>("Floor")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BuildingId");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            Id = 11,
                            BuildingId = 1,
                            CeilingHeight = 3.5,
                            Floor = 1
                        },
                        new
                        {
                            Id = 22,
                            BuildingId = 1,
                            CeilingHeight = 3.0,
                            Floor = 2
                        },
                        new
                        {
                            Id = 33,
                            BuildingId = 1,
                            CeilingHeight = 3.0,
                            Floor = 3
                        },
                        new
                        {
                            Id = 44,
                            BuildingId = 2,
                            CeilingHeight = 3.0,
                            Floor = 1
                        },
                        new
                        {
                            Id = 55,
                            BuildingId = 2,
                            CeilingHeight = 3.0,
                            Floor = 2
                        });
                });

            modelBuilder.Entity("ASPNETCoreApp.Models.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<double>("Area")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("float")
                        .HasComputedColumnSql("[Width]*[Length]", true);

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<double>("Length")
                        .HasColumnType("float");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<int>("Purpose")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<double>("Width")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("LocationId");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Area = 0.0,
                            DepartmentId = 1,
                            Length = 13.0,
                            LocationId = 11,
                            Number = 23,
                            Purpose = 0,
                            Type = 1,
                            Width = 13.0
                        },
                        new
                        {
                            Id = 2,
                            Area = 0.0,
                            DepartmentId = 1,
                            Length = 18.0,
                            LocationId = 11,
                            Number = 19,
                            Purpose = 1,
                            Type = 1,
                            Width = 10.0
                        },
                        new
                        {
                            Id = 3,
                            Area = 0.0,
                            DepartmentId = 1,
                            Length = 14.0,
                            LocationId = 11,
                            Number = 12,
                            Purpose = 1,
                            Type = 1,
                            Width = 11.0
                        },
                        new
                        {
                            Id = 4,
                            Area = 0.0,
                            DepartmentId = 1,
                            Length = 11.0,
                            LocationId = 11,
                            Number = 17,
                            Purpose = 1,
                            Type = 1,
                            Width = 10.0
                        },
                        new
                        {
                            Id = 6,
                            Area = 0.0,
                            DepartmentId = 1,
                            Length = 14.0,
                            LocationId = 11,
                            Number = 22,
                            Purpose = 1,
                            Type = 1,
                            Width = 8.0
                        },
                        new
                        {
                            Id = 7,
                            Area = 0.0,
                            DepartmentId = 1,
                            Length = 20.0,
                            LocationId = 11,
                            Number = 9,
                            Purpose = 1,
                            Type = 0,
                            Width = 12.0
                        },
                        new
                        {
                            Id = 8,
                            Area = 0.0,
                            DepartmentId = 1,
                            Length = 15.0,
                            LocationId = 11,
                            Number = 4,
                            Purpose = 0,
                            Type = 0,
                            Width = 11.0
                        },
                        new
                        {
                            Id = 9,
                            Area = 0.0,
                            DepartmentId = 1,
                            Length = 16.0,
                            LocationId = 11,
                            Number = 21,
                            Purpose = 0,
                            Type = 1,
                            Width = 10.0
                        },
                        new
                        {
                            Id = 10,
                            Area = 0.0,
                            DepartmentId = 1,
                            Length = 7.0,
                            LocationId = 11,
                            Number = 10,
                            Purpose = 0,
                            Type = 0,
                            Width = 13.0
                        },
                        new
                        {
                            Id = 11,
                            Area = 0.0,
                            DepartmentId = 1,
                            Length = 11.0,
                            LocationId = 11,
                            Number = 14,
                            Purpose = 0,
                            Type = 0,
                            Width = 14.0
                        },
                        new
                        {
                            Id = 12,
                            Area = 0.0,
                            DepartmentId = 1,
                            Length = 14.0,
                            LocationId = 11,
                            Number = 1,
                            Purpose = 0,
                            Type = 1,
                            Width = 8.0
                        },
                        new
                        {
                            Id = 13,
                            Area = 0.0,
                            DepartmentId = 1,
                            Length = 20.0,
                            LocationId = 11,
                            Number = 18,
                            Purpose = 0,
                            Type = 1,
                            Width = 14.0
                        },
                        new
                        {
                            Id = 14,
                            Area = 0.0,
                            DepartmentId = 1,
                            Length = 7.0,
                            LocationId = 11,
                            Number = 24,
                            Purpose = 1,
                            Type = 0,
                            Width = 8.0
                        },
                        new
                        {
                            Id = 16,
                            Area = 0.0,
                            DepartmentId = 1,
                            Length = 14.0,
                            LocationId = 11,
                            Number = 28,
                            Purpose = 0,
                            Type = 1,
                            Width = 12.0
                        },
                        new
                        {
                            Id = 17,
                            Area = 0.0,
                            DepartmentId = 1,
                            Length = 11.0,
                            LocationId = 11,
                            Number = 31,
                            Purpose = 1,
                            Type = 0,
                            Width = 6.0
                        },
                        new
                        {
                            Id = 19,
                            Area = 0.0,
                            DepartmentId = 1,
                            Length = 6.0,
                            LocationId = 11,
                            Number = 25,
                            Purpose = 0,
                            Type = 1,
                            Width = 9.0
                        },
                        new
                        {
                            Id = 20,
                            Area = 0.0,
                            DepartmentId = 1,
                            Length = 18.0,
                            LocationId = 11,
                            Number = 8,
                            Purpose = 0,
                            Type = 1,
                            Width = 12.0
                        },
                        new
                        {
                            Id = 25,
                            Area = 0.0,
                            DepartmentId = 1,
                            Length = 10.0,
                            LocationId = 11,
                            Number = 11,
                            Purpose = 0,
                            Type = 0,
                            Width = 14.0
                        },
                        new
                        {
                            Id = 27,
                            Area = 0.0,
                            DepartmentId = 1,
                            Length = 19.0,
                            LocationId = 11,
                            Number = 27,
                            Purpose = 0,
                            Type = 1,
                            Width = 14.0
                        },
                        new
                        {
                            Id = 29,
                            Area = 0.0,
                            DepartmentId = 1,
                            Length = 15.0,
                            LocationId = 11,
                            Number = 7,
                            Purpose = 0,
                            Type = 0,
                            Width = 16.0
                        },
                        new
                        {
                            Id = 33,
                            Area = 0.0,
                            DepartmentId = 2,
                            Length = 14.0,
                            LocationId = 22,
                            Number = 55,
                            Purpose = 1,
                            Type = 0,
                            Width = 9.0
                        },
                        new
                        {
                            Id = 34,
                            Area = 0.0,
                            DepartmentId = 2,
                            Length = 20.0,
                            LocationId = 22,
                            Number = 43,
                            Purpose = 0,
                            Type = 0,
                            Width = 6.0
                        },
                        new
                        {
                            Id = 35,
                            Area = 0.0,
                            DepartmentId = 2,
                            Length = 16.0,
                            LocationId = 22,
                            Number = 38,
                            Purpose = 1,
                            Type = 1,
                            Width = 14.0
                        },
                        new
                        {
                            Id = 36,
                            Area = 0.0,
                            DepartmentId = 2,
                            Length = 17.0,
                            LocationId = 22,
                            Number = 41,
                            Purpose = 1,
                            Type = 0,
                            Width = 10.0
                        },
                        new
                        {
                            Id = 39,
                            Area = 0.0,
                            DepartmentId = 2,
                            Length = 13.0,
                            LocationId = 22,
                            Number = 51,
                            Purpose = 0,
                            Type = 1,
                            Width = 12.0
                        },
                        new
                        {
                            Id = 40,
                            Area = 0.0,
                            DepartmentId = 2,
                            Length = 20.0,
                            LocationId = 22,
                            Number = 50,
                            Purpose = 1,
                            Type = 0,
                            Width = 15.0
                        },
                        new
                        {
                            Id = 41,
                            Area = 0.0,
                            DepartmentId = 2,
                            Length = 9.0,
                            LocationId = 22,
                            Number = 45,
                            Purpose = 1,
                            Type = 0,
                            Width = 6.0
                        },
                        new
                        {
                            Id = 42,
                            Area = 0.0,
                            DepartmentId = 2,
                            Length = 16.0,
                            LocationId = 22,
                            Number = 63,
                            Purpose = 0,
                            Type = 1,
                            Width = 9.0
                        },
                        new
                        {
                            Id = 43,
                            Area = 0.0,
                            DepartmentId = 2,
                            Length = 18.0,
                            LocationId = 22,
                            Number = 64,
                            Purpose = 1,
                            Type = 1,
                            Width = 10.0
                        },
                        new
                        {
                            Id = 45,
                            Area = 0.0,
                            DepartmentId = 2,
                            Length = 17.0,
                            LocationId = 22,
                            Number = 46,
                            Purpose = 0,
                            Type = 1,
                            Width = 15.0
                        },
                        new
                        {
                            Id = 46,
                            Area = 0.0,
                            DepartmentId = 2,
                            Length = 10.0,
                            LocationId = 22,
                            Number = 35,
                            Purpose = 0,
                            Type = 1,
                            Width = 9.0
                        },
                        new
                        {
                            Id = 47,
                            Area = 0.0,
                            DepartmentId = 2,
                            Length = 9.0,
                            LocationId = 22,
                            Number = 61,
                            Purpose = 1,
                            Type = 0,
                            Width = 14.0
                        },
                        new
                        {
                            Id = 48,
                            Area = 0.0,
                            DepartmentId = 2,
                            Length = 10.0,
                            LocationId = 22,
                            Number = 47,
                            Purpose = 0,
                            Type = 0,
                            Width = 10.0
                        },
                        new
                        {
                            Id = 50,
                            Area = 0.0,
                            DepartmentId = 2,
                            Length = 9.0,
                            LocationId = 22,
                            Number = 57,
                            Purpose = 1,
                            Type = 1,
                            Width = 6.0
                        },
                        new
                        {
                            Id = 51,
                            Area = 0.0,
                            DepartmentId = 2,
                            Length = 11.0,
                            LocationId = 22,
                            Number = 44,
                            Purpose = 0,
                            Type = 1,
                            Width = 11.0
                        },
                        new
                        {
                            Id = 53,
                            Area = 0.0,
                            DepartmentId = 2,
                            Length = 6.0,
                            LocationId = 22,
                            Number = 33,
                            Purpose = 1,
                            Type = 1,
                            Width = 9.0
                        },
                        new
                        {
                            Id = 58,
                            Area = 0.0,
                            DepartmentId = 2,
                            Length = 12.0,
                            LocationId = 22,
                            Number = 48,
                            Purpose = 1,
                            Type = 0,
                            Width = 12.0
                        },
                        new
                        {
                            Id = 59,
                            Area = 0.0,
                            DepartmentId = 2,
                            Length = 7.0,
                            LocationId = 22,
                            Number = 62,
                            Purpose = 1,
                            Type = 1,
                            Width = 12.0
                        },
                        new
                        {
                            Id = 62,
                            Area = 0.0,
                            DepartmentId = 2,
                            Length = 8.0,
                            LocationId = 22,
                            Number = 52,
                            Purpose = 0,
                            Type = 0,
                            Width = 12.0
                        },
                        new
                        {
                            Id = 66,
                            Area = 0.0,
                            DepartmentId = 3,
                            Length = 19.0,
                            LocationId = 33,
                            Number = 111,
                            Purpose = 0,
                            Type = 0,
                            Width = 12.0
                        },
                        new
                        {
                            Id = 67,
                            Area = 0.0,
                            DepartmentId = 3,
                            Length = 6.0,
                            LocationId = 33,
                            Number = 68,
                            Purpose = 0,
                            Type = 0,
                            Width = 10.0
                        },
                        new
                        {
                            Id = 68,
                            Area = 0.0,
                            DepartmentId = 3,
                            Length = 12.0,
                            LocationId = 33,
                            Number = 97,
                            Purpose = 1,
                            Type = 0,
                            Width = 9.0
                        },
                        new
                        {
                            Id = 69,
                            Area = 0.0,
                            DepartmentId = 3,
                            Length = 20.0,
                            LocationId = 33,
                            Number = 67,
                            Purpose = 1,
                            Type = 1,
                            Width = 12.0
                        },
                        new
                        {
                            Id = 70,
                            Area = 0.0,
                            DepartmentId = 3,
                            Length = 11.0,
                            LocationId = 33,
                            Number = 73,
                            Purpose = 1,
                            Type = 1,
                            Width = 13.0
                        },
                        new
                        {
                            Id = 71,
                            Area = 0.0,
                            DepartmentId = 3,
                            Length = 17.0,
                            LocationId = 33,
                            Number = 95,
                            Purpose = 1,
                            Type = 0,
                            Width = 9.0
                        },
                        new
                        {
                            Id = 72,
                            Area = 0.0,
                            DepartmentId = 3,
                            Length = 10.0,
                            LocationId = 33,
                            Number = 106,
                            Purpose = 0,
                            Type = 1,
                            Width = 14.0
                        },
                        new
                        {
                            Id = 73,
                            Area = 0.0,
                            DepartmentId = 3,
                            Length = 15.0,
                            LocationId = 33,
                            Number = 101,
                            Purpose = 1,
                            Type = 1,
                            Width = 8.0
                        },
                        new
                        {
                            Id = 74,
                            Area = 0.0,
                            DepartmentId = 3,
                            Length = 13.0,
                            LocationId = 33,
                            Number = 105,
                            Purpose = 0,
                            Type = 1,
                            Width = 8.0
                        },
                        new
                        {
                            Id = 75,
                            Area = 0.0,
                            DepartmentId = 3,
                            Length = 7.0,
                            LocationId = 33,
                            Number = 69,
                            Purpose = 0,
                            Type = 0,
                            Width = 15.0
                        },
                        new
                        {
                            Id = 76,
                            Area = 0.0,
                            DepartmentId = 3,
                            Length = 10.0,
                            LocationId = 33,
                            Number = 89,
                            Purpose = 0,
                            Type = 1,
                            Width = 16.0
                        },
                        new
                        {
                            Id = 77,
                            Area = 0.0,
                            DepartmentId = 3,
                            Length = 17.0,
                            LocationId = 33,
                            Number = 76,
                            Purpose = 1,
                            Type = 0,
                            Width = 9.0
                        },
                        new
                        {
                            Id = 78,
                            Area = 0.0,
                            DepartmentId = 3,
                            Length = 8.0,
                            LocationId = 33,
                            Number = 84,
                            Purpose = 0,
                            Type = 1,
                            Width = 11.0
                        },
                        new
                        {
                            Id = 79,
                            Area = 0.0,
                            DepartmentId = 3,
                            Length = 16.0,
                            LocationId = 33,
                            Number = 77,
                            Purpose = 1,
                            Type = 1,
                            Width = 7.0
                        },
                        new
                        {
                            Id = 80,
                            Area = 0.0,
                            DepartmentId = 3,
                            Length = 17.0,
                            LocationId = 33,
                            Number = 119,
                            Purpose = 1,
                            Type = 0,
                            Width = 12.0
                        },
                        new
                        {
                            Id = 81,
                            Area = 0.0,
                            DepartmentId = 3,
                            Length = 19.0,
                            LocationId = 33,
                            Number = 72,
                            Purpose = 1,
                            Type = 1,
                            Width = 10.0
                        },
                        new
                        {
                            Id = 82,
                            Area = 0.0,
                            DepartmentId = 3,
                            Length = 20.0,
                            LocationId = 33,
                            Number = 94,
                            Purpose = 0,
                            Type = 0,
                            Width = 13.0
                        },
                        new
                        {
                            Id = 84,
                            Area = 0.0,
                            DepartmentId = 3,
                            Length = 15.0,
                            LocationId = 33,
                            Number = 70,
                            Purpose = 1,
                            Type = 0,
                            Width = 7.0
                        },
                        new
                        {
                            Id = 85,
                            Area = 0.0,
                            DepartmentId = 3,
                            Length = 17.0,
                            LocationId = 33,
                            Number = 99,
                            Purpose = 1,
                            Type = 0,
                            Width = 11.0
                        },
                        new
                        {
                            Id = 86,
                            Area = 0.0,
                            DepartmentId = 3,
                            Length = 18.0,
                            LocationId = 33,
                            Number = 78,
                            Purpose = 1,
                            Type = 1,
                            Width = 6.0
                        },
                        new
                        {
                            Id = 89,
                            Area = 0.0,
                            DepartmentId = 3,
                            Length = 12.0,
                            LocationId = 33,
                            Number = 127,
                            Purpose = 1,
                            Type = 1,
                            Width = 11.0
                        },
                        new
                        {
                            Id = 91,
                            Area = 0.0,
                            DepartmentId = 3,
                            Length = 10.0,
                            LocationId = 33,
                            Number = 86,
                            Purpose = 0,
                            Type = 0,
                            Width = 8.0
                        },
                        new
                        {
                            Id = 93,
                            Area = 0.0,
                            DepartmentId = 3,
                            Length = 16.0,
                            LocationId = 33,
                            Number = 129,
                            Purpose = 1,
                            Type = 0,
                            Width = 7.0
                        },
                        new
                        {
                            Id = 94,
                            Area = 0.0,
                            DepartmentId = 3,
                            Length = 16.0,
                            LocationId = 33,
                            Number = 121,
                            Purpose = 0,
                            Type = 1,
                            Width = 15.0
                        },
                        new
                        {
                            Id = 95,
                            Area = 0.0,
                            DepartmentId = 3,
                            Length = 18.0,
                            LocationId = 33,
                            Number = 100,
                            Purpose = 0,
                            Type = 1,
                            Width = 6.0
                        },
                        new
                        {
                            Id = 96,
                            Area = 0.0,
                            DepartmentId = 3,
                            Length = 14.0,
                            LocationId = 33,
                            Number = 107,
                            Purpose = 0,
                            Type = 1,
                            Width = 8.0
                        },
                        new
                        {
                            Id = 97,
                            Area = 0.0,
                            DepartmentId = 3,
                            Length = 14.0,
                            LocationId = 33,
                            Number = 110,
                            Purpose = 1,
                            Type = 1,
                            Width = 10.0
                        },
                        new
                        {
                            Id = 98,
                            Area = 0.0,
                            DepartmentId = 3,
                            Length = 18.0,
                            LocationId = 33,
                            Number = 75,
                            Purpose = 1,
                            Type = 0,
                            Width = 14.0
                        },
                        new
                        {
                            Id = 100,
                            Area = 0.0,
                            DepartmentId = 3,
                            Length = 8.0,
                            LocationId = 33,
                            Number = 130,
                            Purpose = 0,
                            Type = 0,
                            Width = 13.0
                        },
                        new
                        {
                            Id = 102,
                            Area = 0.0,
                            DepartmentId = 3,
                            Length = 7.0,
                            LocationId = 33,
                            Number = 116,
                            Purpose = 1,
                            Type = 0,
                            Width = 11.0
                        },
                        new
                        {
                            Id = 103,
                            Area = 0.0,
                            DepartmentId = 3,
                            Length = 13.0,
                            LocationId = 33,
                            Number = 114,
                            Purpose = 0,
                            Type = 0,
                            Width = 15.0
                        },
                        new
                        {
                            Id = 107,
                            Area = 0.0,
                            DepartmentId = 3,
                            Length = 11.0,
                            LocationId = 33,
                            Number = 80,
                            Purpose = 0,
                            Type = 0,
                            Width = 8.0
                        },
                        new
                        {
                            Id = 108,
                            Area = 0.0,
                            DepartmentId = 3,
                            Length = 16.0,
                            LocationId = 33,
                            Number = 85,
                            Purpose = 1,
                            Type = 0,
                            Width = 14.0
                        },
                        new
                        {
                            Id = 109,
                            Area = 0.0,
                            DepartmentId = 3,
                            Length = 19.0,
                            LocationId = 33,
                            Number = 109,
                            Purpose = 0,
                            Type = 1,
                            Width = 11.0
                        },
                        new
                        {
                            Id = 112,
                            Area = 0.0,
                            DepartmentId = 3,
                            Length = 6.0,
                            LocationId = 33,
                            Number = 124,
                            Purpose = 0,
                            Type = 1,
                            Width = 14.0
                        },
                        new
                        {
                            Id = 113,
                            Area = 0.0,
                            DepartmentId = 3,
                            Length = 15.0,
                            LocationId = 33,
                            Number = 74,
                            Purpose = 1,
                            Type = 0,
                            Width = 7.0
                        },
                        new
                        {
                            Id = 116,
                            Area = 0.0,
                            DepartmentId = 3,
                            Length = 11.0,
                            LocationId = 33,
                            Number = 90,
                            Purpose = 0,
                            Type = 1,
                            Width = 7.0
                        },
                        new
                        {
                            Id = 117,
                            Area = 0.0,
                            DepartmentId = 3,
                            Length = 20.0,
                            LocationId = 33,
                            Number = 112,
                            Purpose = 0,
                            Type = 1,
                            Width = 12.0
                        },
                        new
                        {
                            Id = 118,
                            Area = 0.0,
                            DepartmentId = 3,
                            Length = 11.0,
                            LocationId = 33,
                            Number = 123,
                            Purpose = 1,
                            Type = 0,
                            Width = 11.0
                        },
                        new
                        {
                            Id = 119,
                            Area = 0.0,
                            DepartmentId = 3,
                            Length = 18.0,
                            LocationId = 33,
                            Number = 102,
                            Purpose = 1,
                            Type = 0,
                            Width = 8.0
                        },
                        new
                        {
                            Id = 122,
                            Area = 0.0,
                            DepartmentId = 3,
                            Length = 12.0,
                            LocationId = 33,
                            Number = 125,
                            Purpose = 1,
                            Type = 0,
                            Width = 11.0
                        },
                        new
                        {
                            Id = 124,
                            Area = 0.0,
                            DepartmentId = 3,
                            Length = 17.0,
                            LocationId = 33,
                            Number = 81,
                            Purpose = 1,
                            Type = 1,
                            Width = 12.0
                        },
                        new
                        {
                            Id = 126,
                            Area = 0.0,
                            DepartmentId = 3,
                            Length = 7.0,
                            LocationId = 33,
                            Number = 118,
                            Purpose = 0,
                            Type = 1,
                            Width = 14.0
                        },
                        new
                        {
                            Id = 127,
                            Area = 0.0,
                            DepartmentId = 3,
                            Length = 6.0,
                            LocationId = 33,
                            Number = 117,
                            Purpose = 0,
                            Type = 1,
                            Width = 6.0
                        },
                        new
                        {
                            Id = 132,
                            Area = 0.0,
                            DepartmentId = 4,
                            Length = 17.0,
                            LocationId = 44,
                            Number = 135,
                            Purpose = 1,
                            Type = 0,
                            Width = 10.0
                        },
                        new
                        {
                            Id = 133,
                            Area = 0.0,
                            DepartmentId = 4,
                            Length = 12.0,
                            LocationId = 44,
                            Number = 145,
                            Purpose = 1,
                            Type = 0,
                            Width = 12.0
                        },
                        new
                        {
                            Id = 134,
                            Area = 0.0,
                            DepartmentId = 4,
                            Length = 16.0,
                            LocationId = 44,
                            Number = 160,
                            Purpose = 1,
                            Type = 0,
                            Width = 12.0
                        },
                        new
                        {
                            Id = 135,
                            Area = 0.0,
                            DepartmentId = 4,
                            Length = 12.0,
                            LocationId = 44,
                            Number = 158,
                            Purpose = 0,
                            Type = 0,
                            Width = 8.0
                        },
                        new
                        {
                            Id = 136,
                            Area = 0.0,
                            DepartmentId = 4,
                            Length = 20.0,
                            LocationId = 44,
                            Number = 134,
                            Purpose = 0,
                            Type = 0,
                            Width = 9.0
                        },
                        new
                        {
                            Id = 137,
                            Area = 0.0,
                            DepartmentId = 4,
                            Length = 16.0,
                            LocationId = 44,
                            Number = 147,
                            Purpose = 0,
                            Type = 1,
                            Width = 15.0
                        },
                        new
                        {
                            Id = 139,
                            Area = 0.0,
                            DepartmentId = 4,
                            Length = 12.0,
                            LocationId = 44,
                            Number = 133,
                            Purpose = 1,
                            Type = 0,
                            Width = 11.0
                        },
                        new
                        {
                            Id = 140,
                            Area = 0.0,
                            DepartmentId = 4,
                            Length = 8.0,
                            LocationId = 44,
                            Number = 157,
                            Purpose = 0,
                            Type = 1,
                            Width = 6.0
                        },
                        new
                        {
                            Id = 141,
                            Area = 0.0,
                            DepartmentId = 4,
                            Length = 17.0,
                            LocationId = 44,
                            Number = 153,
                            Purpose = 0,
                            Type = 0,
                            Width = 14.0
                        },
                        new
                        {
                            Id = 142,
                            Area = 0.0,
                            DepartmentId = 4,
                            Length = 14.0,
                            LocationId = 44,
                            Number = 136,
                            Purpose = 0,
                            Type = 0,
                            Width = 12.0
                        },
                        new
                        {
                            Id = 143,
                            Area = 0.0,
                            DepartmentId = 4,
                            Length = 14.0,
                            LocationId = 44,
                            Number = 163,
                            Purpose = 1,
                            Type = 1,
                            Width = 11.0
                        },
                        new
                        {
                            Id = 147,
                            Area = 0.0,
                            DepartmentId = 4,
                            Length = 10.0,
                            LocationId = 44,
                            Number = 151,
                            Purpose = 1,
                            Type = 0,
                            Width = 16.0
                        },
                        new
                        {
                            Id = 148,
                            Area = 0.0,
                            DepartmentId = 4,
                            Length = 6.0,
                            LocationId = 44,
                            Number = 143,
                            Purpose = 1,
                            Type = 1,
                            Width = 7.0
                        },
                        new
                        {
                            Id = 149,
                            Area = 0.0,
                            DepartmentId = 4,
                            Length = 16.0,
                            LocationId = 44,
                            Number = 156,
                            Purpose = 1,
                            Type = 0,
                            Width = 8.0
                        },
                        new
                        {
                            Id = 153,
                            Area = 0.0,
                            DepartmentId = 4,
                            Length = 7.0,
                            LocationId = 44,
                            Number = 148,
                            Purpose = 1,
                            Type = 0,
                            Width = 10.0
                        },
                        new
                        {
                            Id = 154,
                            Area = 0.0,
                            DepartmentId = 4,
                            Length = 13.0,
                            LocationId = 44,
                            Number = 149,
                            Purpose = 0,
                            Type = 0,
                            Width = 10.0
                        },
                        new
                        {
                            Id = 155,
                            Area = 0.0,
                            DepartmentId = 4,
                            Length = 15.0,
                            LocationId = 44,
                            Number = 154,
                            Purpose = 0,
                            Type = 1,
                            Width = 10.0
                        },
                        new
                        {
                            Id = 157,
                            Area = 0.0,
                            DepartmentId = 4,
                            Length = 11.0,
                            LocationId = 44,
                            Number = 161,
                            Purpose = 1,
                            Type = 0,
                            Width = 8.0
                        },
                        new
                        {
                            Id = 158,
                            Area = 0.0,
                            DepartmentId = 4,
                            Length = 12.0,
                            LocationId = 44,
                            Number = 139,
                            Purpose = 1,
                            Type = 0,
                            Width = 10.0
                        },
                        new
                        {
                            Id = 159,
                            Area = 0.0,
                            DepartmentId = 4,
                            Length = 15.0,
                            LocationId = 44,
                            Number = 155,
                            Purpose = 0,
                            Type = 0,
                            Width = 6.0
                        },
                        new
                        {
                            Id = 160,
                            Area = 0.0,
                            DepartmentId = 4,
                            Length = 8.0,
                            LocationId = 44,
                            Number = 137,
                            Purpose = 0,
                            Type = 0,
                            Width = 14.0
                        },
                        new
                        {
                            Id = 165,
                            Area = 0.0,
                            DepartmentId = 5,
                            Length = 9.0,
                            LocationId = 55,
                            Number = 166,
                            Purpose = 0,
                            Type = 1,
                            Width = 8.0
                        },
                        new
                        {
                            Id = 166,
                            Area = 0.0,
                            DepartmentId = 5,
                            Length = 7.0,
                            LocationId = 55,
                            Number = 172,
                            Purpose = 1,
                            Type = 1,
                            Width = 12.0
                        },
                        new
                        {
                            Id = 167,
                            Area = 0.0,
                            DepartmentId = 5,
                            Length = 8.0,
                            LocationId = 55,
                            Number = 167,
                            Purpose = 1,
                            Type = 0,
                            Width = 10.0
                        },
                        new
                        {
                            Id = 168,
                            Area = 0.0,
                            DepartmentId = 5,
                            Length = 9.0,
                            LocationId = 55,
                            Number = 179,
                            Purpose = 1,
                            Type = 1,
                            Width = 12.0
                        },
                        new
                        {
                            Id = 170,
                            Area = 0.0,
                            DepartmentId = 5,
                            Length = 7.0,
                            LocationId = 55,
                            Number = 176,
                            Purpose = 0,
                            Type = 0,
                            Width = 9.0
                        },
                        new
                        {
                            Id = 171,
                            Area = 0.0,
                            DepartmentId = 5,
                            Length = 14.0,
                            LocationId = 55,
                            Number = 174,
                            Purpose = 0,
                            Type = 1,
                            Width = 14.0
                        },
                        new
                        {
                            Id = 174,
                            Area = 0.0,
                            DepartmentId = 5,
                            Length = 13.0,
                            LocationId = 55,
                            Number = 177,
                            Purpose = 0,
                            Type = 0,
                            Width = 15.0
                        },
                        new
                        {
                            Id = 175,
                            Area = 0.0,
                            DepartmentId = 5,
                            Length = 20.0,
                            LocationId = 55,
                            Number = 171,
                            Purpose = 0,
                            Type = 0,
                            Width = 9.0
                        },
                        new
                        {
                            Id = 176,
                            Area = 0.0,
                            DepartmentId = 5,
                            Length = 12.0,
                            LocationId = 55,
                            Number = 173,
                            Purpose = 1,
                            Type = 0,
                            Width = 10.0
                        },
                        new
                        {
                            Id = 177,
                            Area = 0.0,
                            DepartmentId = 5,
                            Length = 7.0,
                            LocationId = 55,
                            Number = 168,
                            Purpose = 1,
                            Type = 0,
                            Width = 9.0
                        });
                });

            modelBuilder.Entity("ASPNETCoreApp.Models.Department", b =>
                {
                    b.HasOne("ASPNETCoreApp.Models.Faculty", "Faculty")
                        .WithMany("Departments")
                        .HasForeignKey("FacultyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Faculty");
                });

            modelBuilder.Entity("ASPNETCoreApp.Models.Faculty", b =>
                {
                    b.HasOne("ASPNETCoreApp.Models.Building", "Building")
                        .WithMany("Faculties")
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Building");
                });

            modelBuilder.Entity("ASPNETCoreApp.Models.Location", b =>
                {
                    b.HasOne("ASPNETCoreApp.Models.Building", "Building")
                        .WithMany("Locations")
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Building");
                });

            modelBuilder.Entity("ASPNETCoreApp.Models.Room", b =>
                {
                    b.HasOne("ASPNETCoreApp.Models.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId");

                    b.HasOne("ASPNETCoreApp.Models.Location", "Location")
                        .WithMany("Rooms")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("ASPNETCoreApp.Models.Building", b =>
                {
                    b.Navigation("Faculties");

                    b.Navigation("Locations");
                });

            modelBuilder.Entity("ASPNETCoreApp.Models.Faculty", b =>
                {
                    b.Navigation("Departments");
                });

            modelBuilder.Entity("ASPNETCoreApp.Models.Location", b =>
                {
                    b.Navigation("Rooms");
                });
#pragma warning restore 612, 618
        }
    }
}
